name: Run Notebook on Sheet Input

on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 minutes
  workflow_dispatch:       # allows manual run

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install gspread oauth2client nbconvert nbformat papermill

      - name: Authenticate to Google
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > creds.json
          export GOOGLE_APPLICATION_CREDENTIALS=creds.json
          python run_colab.py

      - name: Commit result (optional)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Notebook run" || echo "No changes"
          git push
